sleep_time: 0.25

datasets:
  medqa:
    file_path: "datasets/MedQA/phrases_no_exclude_test.jsonl"
    format_prompt: |
      Only and only answer with the following format:
      <a>{the correct answer option from A, B, C, or D. The letter should be in capital.}</a>
      No explanation, no other text, no other format.
    output_dir: "evaluate_sml/results/medqa/"