sleep_time: 0.2

models:
  Qwen/Qwen2.5-72B-Instruct:
    thinking: false
    temperature: 0.7
    max_tokens_by_prompt_type:
      "Only Final Answer": 100
      "Chain of Thought": 5000
      "Chain of Thought and Think Abductively": 100
  meta-llama/Llama-4-Scout-17B-16E-Instruct:
    thinking: false
    temperature: 0.7
    max_tokens_by_prompt_type:
      "Only Final Answer": 100
      "Chain of Thought": 5000
      "Chain of Thought and Think Abductively": 5000

datasets:
  medqa:
    file_path: "datasets/MedQA/phrases_no_exclude_test.jsonl"
    prompts:
      - type: "Only Final Answer"
        content: |
          Only and only answer with the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid outputs:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
          Output no explanation, no other text, no other format. Output just two tags and the answer within them.
      - type: "Chain of Thought"
        content: |
          Think step by step and thoroughly.
          Output your reasoning and then the final answer of choice.
          The final answer should be in the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid final answers:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
      - type: "Chain of Thought and Think Abductively"
        content: |
          Think step by step and thoroughly. Use abductive reasoning process to reason about the question and the answer choices.
          Output your reasoning and then the final answer of choice.
          The final answer should be in the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid final answers:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
    output_dir: "evaluate_sml/results/medqa/"
  medmcqa:
    hf_path: "openlifescienceai/medmcqa"
    prompts:
      - type: "Only Final Answer"
        content: |
          Only and only answer with the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid outputs:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
          Output no explanation, no other text, no other format. Output just two tags and the answer within them.
      - type: "Chain of Thought"
        content: |
          Think step by step and thoroughly.
          Output your reasoning and then the final answer of choice.
          The final answer should be in the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid final answers:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
      - type: "Chain of Thought and Think Abductively"
        content: |
          Think step by step and thoroughly. Use abductive reasoning process to reason about the question and the answer choices.
          Output your reasoning and then the final answer of choice.
          The final answer should be in the following format:
          Your answer of choice should be wrapped around <a> and </a> tags.
          Valid final answers:
          - <a>A</a>
          - <a>B</a>
          - <a>C</a>
          - <a>D</a>
    output_dir: "evaluate_sml/results/medmcqa/"
